# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_sentiment": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://trancept.github.io/nbdev_flask-api_docker_demo/one_ai_to_rule_them_all/"

git_url = "https://github.trancept.com/nbdev_flask-api_docker_demo/one_ai_to_rule_them_all/tree/master/"

def custom_doc_links(name): return None
