# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['get_sentiment']

# Cell
from flair.models import TextClassifier
from flair.data import Sentence

def get_sentiment(message):
    classifier = TextClassifier.load('en-sentiment') # rely on sentiment-en-mix-distillbert.pt
    sentence = Sentence(message)
    classifier.predict(sentence)
    #print('Sentence sentiment: ', sentence.labels)
    label = sentence.labels[0]
    return {'result': label.value, 'polarity':label.score}